module.exports = {
  URL_WS: "http://localhost:3000/",
  PROSPECT_WS: '/fetch/prospect',
  DELEGATE_WS: '/fetch/delegue',
  VENTES_WS: '/fetch/vente',
  LOGOUT_WS: '/authweb/logout',
  PRODUITS_WS: '/fetch/produit',
  VISITS_WS: '/fetch/visite',
  COMMUNE_WS: '/fetch/commune',

  // Route_View
  VIEW_WORKSPACE: '/workspace',
  VIEW_MAIN: '/home',
  VIEW_PROCESSING: '/processing',
  VIEW_OOREEDOO_CARDS:'/ooreedooCards',
  VIEW_CARDS_DISPO:'/dispoCards',
  VIEW_ORANGE_CARDS:'/orangeCards',
  VIEW_TELECOM_CARDS:'/telecomCards',
  VIEW_ADD_FORM:'/addCards',
  VIEW_COMMANDES:'/commandes',
  VIEW_NEW_COMMANDES:'/newCommandes',
  VIEW_Patients: '/patients',
  VIEW_PENDING_COMMANDES:'/enCoursCommandes',
  VIEW_FINISHED_COMMANDES:'/finishedCommandes',
  VIEW_OOREEDOO_PRICES:'/ooreedooPrices',
  VIEW_ORANGE_PRICES:'/orangePrices',
  VIEW_TELECOM_PRICES:'/telecomPrices',
  VIEW_CONSULTATION:'/consultation',
  VIEW_RDV: '/rdv',
  VIEW_NOTE: '/note',
  VIEW_DOCTORS:'/doctors',
  VIEW_LOGIN: '/login',
  WS_URL: 'http://localhost/',
  DATE_FORMAT: 'DD/MM/Y',
  PROD_URL_PREFIX: '/cabinet',
};
